In [1]:
# Importando Numpy
import numpy as np

In [2]:
#1) Como acessar e alterar os valores do array?
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f'Valores originais do array: {arr}')   

#Acessando por índice
n = 4
o = 8
p = 0
print(f'Acessando diretamente posicao {n} do array: {arr[n]}')
#Acessando slice
print(f'Acessando posições por slice: {arr[p:n-1]}, {arr[:]}, {arr[n:o]}')

#Alterando valores do array com ufunc
def altera_impares(arr):
    if (arr % 2 != 0):
        arr = arr -1 
    return arr

altera_impares = np.frompyfunc(altera_impares, 1, 1)
    
print(f'Novos valores do array: {altera_impares(arr)}')    

#Alterando o tipo de dado do array
print(f'Tipo original do array: {arr.dtype}')
arr = arr.astype('int64')
print(f'Tipo do array alterado para int64: {arr.dtype}')
arr = arr.astype('float64')
print(f'Tipo do array alterado para float64: {arr.dtype}')

Valores originais do array: [0 1 2 3 4 5 6 7 8 9]
Acessando diretamente posicao 4 do array: 4
Acessando posições por slice: [0 1 2], [0 1 2 3 4 5 6 7 8 9], [4 5 6 7]
Novos valores do array: [0 0 2 2 4 4 6 6 8 8]
Tipo original do array: int32
Tipo do array alterado para int64: int64
Tipo do array alterado para float64: float64


In [3]:
#2) Como empilhar dois arrays verticalmente?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

'''Saída desejada:
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])
'''

print(f'Array A: \n {a}\n')
print(f'Array B: \n {b}\n')
print(f'Array A empilhado em B:')
np.concatenate((a, b))

Array A: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Array B: 
 [[1 1 1 1 1]
 [1 1 1 1 1]]

Array A empilhado em B:


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
#3) Como empilhar dois arrays horizontalmente?
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

'''Saída desejada:
array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])'''

print(f'Array A: \n {a}\n')
print(f'Array B: \n {b}\n')
print(f'Array A empilhado em B horizontalmente:')
np.concatenate((a, b), axis=1)

Array A: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Array B: 
 [[1 1 1 1 1]
 [1 1 1 1 1]]

Array A empilhado em B horizontalmente:


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [5]:
#4) Como criar a seguinte sequência com numpy.
a = np.array([1,2,3])

#Saída desejada:
# array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a1 = np.repeat(a = a, repeats = 3, axis = 0)
a2 = np.tile(A = a, reps = 3)
np.concatenate((a1, a2))

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [6]:
# 5) Como pegar os elementos em comum entre dois arrays?
#Entrada:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
#Saída desejada:
#array([2, 4])

'''#intersectar mais de 2 arrays
from functools import reduce
ab = reduce(np.intersect1d, (a, b))'''

ab = np.intersect1d(a, b)
ab

array([2, 4])

In [8]:
# 6) Como pegar as posições de elementos iguais entre dois arrays?
# Entrada:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# Saída desejada:
# (array([1, 3, 5, 7]),)

idx = np.where(np.in1d(a,b))
idx

(array([1, 3, 5, 7], dtype=int64),)

In [10]:
# 7) Como extrair todos os números em um intervalo desejado?
# Entrada:
a = np.array([2, 6, 1, 9, 10, 3, 27])
# Saída desejada:
# (array([6, 9, 10]),)
b = a[1:5]
result = b[b > 1]
result

array([ 6,  9, 10])

In [12]:
''' 8) Como transformar um array 2D em um array 1D, crie um array 2D
com uma quantidade arbitrária de linhas e colunas e transforme em um array 1D. '''
import random as rand
linha = rand.randint(2,5)
coluna = rand.randint(1,5)
shape = (linha, coluna)
array_2d = np.random.randint(0, 10, shape)
print(f'Array 2 dimensões:\n{array_2d}\n')

array_1d = array_2d.flatten()
print(f'Array 1 dimensão com a função flatten():\n{array_1d}\n')
array_1d = array_2d.ravel()
print(f'Array 1 dimensão com a função ravel():\n{array_1d}\n')
array_1d = array_2d.reshape([1, linha * coluna])
print(f'Array 1 dimensão com a função reshape():\n{array_1d}\n')

Array 2 dimensões:
[[3 9 0]
 [8 4 1]
 [3 3 4]
 [0 2 0]
 [0 9 8]]

Array 1 dimensão com a função flatten():
[3 9 0 8 4 1 3 3 4 0 2 0 0 9 8]

Array 1 dimensão com a função ravel():
[3 9 0 8 4 1 3 3 4 0 2 0 0 9 8]

Array 1 dimensão com a função reshape():
[[3 9 0 8 4 1 3 3 4 0 2 0 0 9 8]]



In [13]:
# 9) Crie uma ufunc para transformar uma imagem colorida em uma imagem em escala de cinza e aplique em um programa.
import cv2

arquivo = 'arquivo/imagem.jpg'
'''# carregando a imagem no OpenCV colorida
escala = 3 # escala colorida
imagem = cv2.imread(arquivo, escala)
cv2.imshow('', imagem)
cv2.waitKey(0)
cv2.destroyAllWindows()'''

# função transforma imagem em cinza
def imagem_cinza(arquivo):
    escala = 0 # escala de cinza
    imagem = cv2.imread(arquivo, escala)      
    return imagem

imagem_cinza = np.frompyfunc(imagem_cinza, 1, 1)
imagem = imagem_cinza(arquivo)

#carrega imagem em tela
cv2.imshow('', imagem) 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
'''10)O seguinte link contém imagens comparativas dos registros dos telescópios Hubble e James Webb de diferentes partes do cosmos.
Faça o download das imagens de um dos registros escolhidos, carregue a imagem com o opencv, e realize os seguintes
processamentos.
a) Crie e aplique filtros para exibir as imagens em cores vermelho, verde e azul separadamente, 
para que possamos observar esses espectros da luz visível separadamente.'''
import cv2
import numpy as np

arquivo = 'arquivo/imagem.png'

# função transforma imagem em cinza
def carregar_imagem(arquivo):
    escala = 3 # escala colorida
    imagem = cv2.imread(arquivo, escala)      
    return imagem

carregar_imagem = np.frompyfunc(carregar_imagem, 1, 1)
imagem = carregar_imagem(arquivo)

#verde
imagem[:,:,0] = 0
imagem[:,:,2] = 0
#carrega imagem em tela
cv2.imshow('', imagem) 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
'''10)O seguinte link contém imagens comparativas dos registros dos telescópios Hubble e James Webb de diferentes partes do cosmos.
Faça o download das imagens de um dos registros escolhidos, carregue a imagem com o opencv, e realize os seguintes
processamentos.
a) Crie e aplique filtros para exibir as imagens em cores vermelho, verde e azul separadamente, 
para que possamos observar esses espectros da luz visível separadamente.'''
import cv2
import numpy as np

arquivo = 'arquivo/imagem.png'

# função transforma imagem em cinza
def carregar_imagem(arquivo):
    escala = 3 # escala colorida
    imagem = cv2.imread(arquivo, escala)      
    return imagem

carregar_imagem = np.frompyfunc(carregar_imagem, 1, 1)
imagem = carregar_imagem(arquivo)

#vermelho
imagem[:,:,0] = 0
imagem[:,:,1] = 0
#carrega imagem em tela
cv2.imshow('', imagem) 
cv2.waitKey(0)

-1

In [16]:
'''10)O seguinte link contém imagens comparativas dos registros dos telescópios Hubble e James Webb de diferentes partes do cosmos.
Faça o download das imagens de um dos registros escolhidos, carregue a imagem com o opencv, e realize os seguintes
processamentos.
a) Crie e aplique filtros para exibir as imagens em cores vermelho, verde e azul separadamente, 
para que possamos observar esses espectros da luz visível separadamente.'''
import cv2
import numpy as np

arquivo = 'arquivo/imagem.png'

# função transforma imagem em cinza
def carregar_imagem(arquivo):
    escala = 3 # escala colorida
    imagem = cv2.imread(arquivo, escala)      
    return imagem

carregar_imagem = np.frompyfunc(carregar_imagem, 1, 1)
imagem = carregar_imagem(arquivo)

#azul
imagem[:,:,1] = 0
imagem[:,:,2] = 0
#carrega imagem em tela
cv2.imshow('', imagem) 
cv2.waitKey(0)

-1

In [17]:
'''b) Crie e aplique um filtro que procure exibir somente (ou quase isso) os pontos mais brilhantes da imagem 
(normalmente estrelas ou galáxias)'''

'''
Para obter valores máximos e mínimos em HSV da cor a ser segmentada, executar o seguinte comando no terminal:
python get_color.py -i '<endereço da imagem>'
-> fazer um retângulo na imagem no local da cor a ser segmentada e apertar a letra 'r' do teclado 
no terminal irão aparecer as medidas em HSV. Alterar as variáveis 'lower' e 'upper'
'''

import cv2
import numpy as np

arquivo = cv2.imread('arquivo/imagem.png')
arquivo = cv2.resize(arquivo, (700,500))
hsv = cv2.cvtColor(arquivo, cv2.COLOR_BGR2HSV)
blur = cv2.medianBlur(hsv ,11)

lower = np.array([0,1,99])
upper = np.array([179,105,255])

mask = cv2.inRange(blur, lower, upper)
res = cv2.bitwise_and(arquivo, arquivo, mask=mask)            

#cv2.imshow("Arquivo",arquivo)
#cv2.imshow("mask ",mask)
cv2.imshow('stack', np.hstack([arquivo, res])) #abre a imagem ao lado da mascara
cv2.waitKey(0)
cv2.destroyAllWindows()