In [1]:
# 1) Importe o numpy como “np” e imprima o número da versão.
import numpy as np
print(f'Versão do Numpy instalada: {np.__version__}')

Versão do Numpy instalada: 1.24.2


In [3]:
# 2) Crie um array 1D com números de 0 a 9.
vetor_ex_2 = np.arange(0, 10, 1)
print(f'Vetor Numpy com posições de 0 a 9: \n{vetor_ex_2}.')

Vetor Numpy com posições de 0 a 9: 
[0 1 2 3 4 5 6 7 8 9].


In [4]:
# 3) Crie uma matriz booleana numpy 3×3 com ‘True’
shape = (3, 3)
matriz_booleana = np.full(shape, True)
print(matriz_booleana)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
# 4) Exiba o array da questão 2 com todos os números ímpares substituídos por -1 sem alterar o array
import numpy.ma as ma
print(vetor_ex_2)
vetor_ex_2_sem_impares = ma.masked_where(vetor_ex_2 % 2 != 0, vetor_ex_2)
vetor_ex_2_sem_impares = vetor_ex_2_sem_impares.filled(-1)
print(vetor_ex_2_sem_impares)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [7]:
# 5) Crie 3 matrizes 200 x 200, cada uma com valores aleatórios entre 0 e 
# 255. Junte as 3 matrizes de modo que uma matriz resultante (200 x 200 x 3) seja criada, 
# então exiba como uma imagem utilizando o opencv
import cv2 

shape = (200, 200)
matriz_aleatoria_1 = np.random.randint(0, 255, shape)
matriz_aleatoria_2 = np.random.randint(0, 255, shape)
matriz_aleatoria_3 = np.random.randint(0, 255, shape)
matriz_resultante = np.zeros((200,200,3))
matriz_resultante[:,:,0] = matriz_aleatoria_1
matriz_resultante[:,:,1] = matriz_aleatoria_2
matriz_resultante[:,:,2] = matriz_aleatoria_3
print(matriz_resultante.shape)

# carregando a imagem no OpenCV
cv2.imshow('Matriz Resultante', matriz_resultante)
cv2.waitKey(0)
cv2.destroyAllWindows()

(200, 200, 3)


In [105]:
# 6) Crie um array bidimensional com numpy (com valores pré-definidos) com M linhas e N colunas e em seguida crie um array
#com N elementos e verifique se existe uma linha do primeiro array que corresponde ao segundo array criado
matriz_6_1 = np.array([[1,2,3,6], [3,2,5,7], [1,1,0,2]])
matriz_6_2 = np.array([[1,2,3,6]])
result = False

#com (a==b).all()
for i in range (len(matriz_6_1)):
    if((matriz_6_1[i] == matriz_6_2).all()):
        result = True
        break
print(f'Há uma linha no primeiro array correspondente ao array dois?\n{result}\n')
    
#com np.array_equal()
for i in range (len(matriz_6_1)):
    if(np.array_equal(matriz_6_1[i], matriz_6_2)):
        result = True
        break
print(f'Há uma linha no primeiro array correspondente ao array dois?\n{result}')

Há uma linha no primeiro array correspondente ao array dois?
True

Há uma linha no primeiro array correspondente ao array dois?
True


In [11]:
# 7) Crie um array de qualquer dimensão com valores de 1 até 10 e após, altere todos os valores pares para o valor 45.
import random as rand
linha = rand.randint(1,5)
coluna = rand.randint(1,5)
shape = (linha, coluna)
matriz_7_original = np.random.randint(0, 255, shape)
matriz_7_mascarada = ma.masked_where(matriz_7_original % 2 == 0, matriz_7_original)
matriz_7_mascarada = matriz_7_mascarada.filled(45)
print(f'Matriz original:\n {matriz_7_original}')
print(f'Matriz mascarada:\n {matriz_7_mascarada}')

Matriz original:
 [[ 80  45  46 214 245]
 [230 121 160 207  93]
 [243  35 105 131 145]
 [  0 124 191 239 243]]
Matriz mascarada:
 [[ 45  45  45  45 245]
 [ 45 121  45 207  93]
 [243  35 105 131 145]
 [ 45  45 191 239 243]]


In [13]:
# 8) Crie um array randômico de tamanho 30 e encontre a média e o desvio padrão.
shape = (1, 30)
matriz_8 = np.random.randint(0, 1000, shape)
media = np.mean(matriz_8, axis=1)
desvio_padrao = np.std(matriz_8, axis=1)
print(f'Média: {media}')
print(f'Desvio Padrao: {desvio_padrao}')

Média: [628.1]
Desvio Padrao: [238.66760009]


In [9]:
# 9) Crie um array randômico de valores inteiros e faça a ordenação desse array
tamanho = rand.randint(1, 10)
shape = (1, tamanho)
matriz_9 = np.random.randint(0, 10, shape)
print(f'Matriz gerada:\n {matriz_9}')
print(f'Matriz ordenada:\n {np.sort(matriz_9)}')

Matriz gerada:
 [[1 6 4]]
Matriz ordenada:
 [[1 4 6]]


In [28]:
#10)Crie um array randômico de valores inteiros, em seguida encontre a moda.
shape = (1, 10)
matriz_10 = np.random.randint(0, 5, shape)
valores, quantidades = np.unique(matriz_10, return_counts=True)
moda = np.argwhere(quantidades == np.max(quantidades))
print(f'Matriz Gerada:\n {matriz_10}')
print(f'Moda:\n {moda}')

Matriz Gerada:
 [[4 1 3 4 3 2 3 4 1 3]]
Moda:
 [[2]]
